name: Maven Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3

    - name: Set up GraalVM
      uses: DeLaGuardo/setup-graalvm@v3 # 确保使用正确的版本
      with:
        graalvm-version: '21.0.0.2' # 此处以正确的版本为准
        java-version: 'java17'

    - name: Set JAVA_HOME
      run: echo "JAVA_HOME=$(java -XshowSettings:properties -version 2>&1 > /dev/null | grep 'java.home' | awk '{print \\\$3}')" >> $GITHUB_ENV
   
    - name: Build with Maven
      run: ./mvnw native:compile -Pnative

    - name: Publish to GitHub Packages Apache Maven
      run: mvn deploy -Pnative -s $GITHUB_WORKSPACE/settings.xml
      env:
        GITHUB_TOKEN: ${{ github.token }}

