name: Build and Upload Spring Boot Native Image with Maven

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    - name: Install GraalVM compatible with Java 17
      uses: gluonhq/setup-graalvm-ce@v1
      with:
        graalvm-version: '21.3.0' # Make sure this version is compatible with Java 17
        java-version: '17'

    - name: Install native-image component
      run: gu install native-image

    - name: Set execute permissions for mvnw
      run: chmod +x ./mvnw

    - name: Build native image with Maven
      run: ./mvnw native:compile -Pnative

    - name: Upload native image from target folder
      uses: actions/upload-artifact@v2
      with:
        name: native-image
        path: target/gpt-4-copilot-0.0.4
