name: Maven Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up GraalVM
      uses: DeLaGuardo/setup-graalvm@5.0
      with:
        graalvm-version: '21.3' # 更新为支持 Java 17 的 GraalVM 版本
        java-version: 'java17' # 确保 Java 版本符合你的需求


    - name: Grant execute permission for mvnw
      run: chmod +x ./mvnw

    - name: Set JAVA_HOME
      run: echo "JAVA_HOME=$(java -XshowSettings:properties -version 2>&1 > /dev/null | grep 'java.home' | awk '{print \\\$3}')" >> $GITHUB_ENV
   
    - name: Build with Maven
      run: ./mvnw native:compile -Pnative

    - name: Publish to GitHub Packages Apache Maven
      run: mvn deploy -Pnative -s $GITHUB_WORKSPACE/settings.xml
      env:
        GITHUB_TOKEN: ${{ github.token }}


